### PR TITLE
Added trail tracks.

### PR DESCRIPTION
**Pull request by Dzierzan**
The purpose of this PR is to add trail track sprites. ST01B is a testcase.

Tracks will require custom code in order to make them work the same way they work in the original game.

### CODE REVIEW

**Comment by IceReaper** [comment]
1. why no vspr here? would void the need for those combine entries
2. what about mechs? do we want footsteps?

**Comment by michaeldgg2** [comment]
> why no vspr here? would void the need for those combine entries

I agree, but he uses `FlipX` *and* `FlipY` for some frames.

> what about mechs? do we want footsteps?

Well, there are tiles with footsteps (sprites 197, 198), but I don't think they're for the mechs.

We would need custom sprites for the mechs anyway.

Anyway, as for the trails themselves with small tweak to `LeavesTrails` trait it looks like this:

opene2140_leavestrails_movinginterval_8

I know it doesn't behave like in E2140 (especially when turning + the disappearance), but this is the fastest way to get to at least a something. I'll prepare PR to OpenRA.

**Comment by Dzierzan** [comment]
> 1. why no vspr here? would void the need for those combine entries
> 2. what about mechs? do we want footsteps?

Because I didn't know how to achieve that by using virtual assets.

**Comment by michaeldgg2** [comment]
Virtual sprites needs support for either vertical flipping or manual horizontal flipping (similar to how flipping works for offsets of virtual sprites) in order to get rid of the `Combine` solution for the tracks spritesheets.

Implemented in 310db17ccbf548dc407de7e93ebb8782fa102605 (trait) and 6ff92e9664f2e0edbb0c7eda0f26b0b8e3fd2b35 (YAMLs)

**Pull request closed without merging**
