### PR TITLE
Husks can be crushed by any vehicle actor.

### PR DESCRIPTION
**Pull request by Dzierzan**

### CODE REVIEW

**Comment by Dzierzan** [comment]
However ship husks do not explode when crushed, I cannot understand why.

**Comment by Dzierzan** [comment]
I fixed the issue. In fact there were no explosions when any ship actor was dead.

**Review by michaeldgg2 — CHANGES_REQUESTED** [review]
Crushing a husk should deal (a small amount of) damage. I tried it on ST 02 (i.e. ST 02 was crushing a husk) and it received 8 points of damage (200hp -> 192hp).

**Comment by Dzierzan** [comment]
Should it deal damage, though?

EDIT: Yeah, I tested it in game, crushing husks really deals damage. But I am not sure if it should be a thing. IMO it's a bit counterintuitive as you are damaging your units and those units are happy to crush those husks.

**Comment by IceReaper** [comment]
Now the question rises: what does the damage? the crushing? or the explosion? or the husk burning the unit a bit?

**Comment by michaeldgg2** [comment]
I think it's the explosion, because husks do not always burn (and the unit crushing it still receives tiny damage).

@Dzierzan the damage is really tiny, so theoretically we can save ourselves some trouble (at least for now).

**Comment by Dzierzan** [comment]
Alright, if you insist.

**Review by michaeldgg2 — APPROVED** [review]

**Pull request merged**
