### PR TITLE
Implemented power plant smoke animation

### LINKED ISSUE #109: Add smoke for power plant
In vanilla game, smoke is affected by wind. Initial version may ignore that effect by now.

### PR DESCRIPTION
**Pull request by michal-mad**
Closes #109

### CODE REVIEW

**Comment by Dzierzan** [comment]
Try this, it will look better:

**rules.yaml:**

```
	FloatingSpriteEmitter:
		Duration: -1
		Lifetime: 27
		SpawnFrequency: 5
		Speed: 5
		Gravity: 35
		RandomRate: 0
		Palette:
		Image: power_plant_smoke
		Sequences: chimney_smoke
		RequiresCondition: !Transforming
	WithIdleOverlay:
		Palette:
		RequiresCondition: !Transforming
```

**sequences.yaml:**


```
shared_buildings_power_plant:
	Defaults:
		Filename: building_power_plant.vspr
		Offset: -10, -20, 0
	idle:
	idle_light:
		Start: 1
	idle-overlay:
		Filename: smoke.vspr
		Offset: 2,-79,0
		Frames: 1,2,3,4
		Length: 3
		Tick: 140
		BlendMode: Additive
	damaged-idle:
		Start: 2
	damaged-idle_light:
		Start: 3
	addon:
		Start: 4
	addon_damaged:
		Start: 5

shared_mcu_power_plant:
	Inherits: shared_mcu
	# TODO remove this!!! We only need faction specific variants!
	icon:
		Filename: SPRI1.MIX
		Start: 183

power_plant_smoke:
	chimney_smoke:
		Filename: smoke.vspr
		Offset: 0,-80,0
		Length: 8
		Tick: 140
		BlendMode: Additive
```

**Comment by michal-mad** [comment]
Applied @Dzierzan suggestions. PR is ready to review/accept.

**Comment by Dzierzan** [comment]
LGTM!

Squish commits, though.

**Comment by michal-mad** [comment]
Done

**Pull request merged**
